---
title: "New Building Project"
output: 
  flexdashboard::flex_dashboard:
   navbar:
    - { title: "About", href: "https://datamonkeysite.com/", align: right }
    
---

```{r setup, include=FALSE}
library(flexdashboard)
```
charts(altair)
=====================================



```{python,python.reticulate = FALSE}

import altair as alt
import pandas as pd
df=pd.read_csv("data/earned.csv",parse_dates=[0], dayfirst=True)

pts = alt.selection(type='multi', encodings=['y'])

barselect = alt.Chart(df).mark_bar().encode(
    y='category:N',
    x='sum(earned)',
    color=alt.condition(pts, alt.ColorValue("steelblue"), alt.ColorValue("grey"))
).properties(
    selection=pts,
    width=550,
    height=200
)   
  
line_earned = alt.Chart(df).transform_filter(
    pts
      ).transform_aggregate(
    sum_installed_cumulative='sum(earned_cumulative)',
    sum_planned_cumulative='sum(planned_cumulative)',
    sum_budget='sum(budget)',
    sum_Installed_qty='sum(earned)',
    groupby=['date']
).transform_calculate(
    earned_cumulative='datum.sum_installed_cumulative / datum.sum_budget',
    planned_cumulative='datum.sum_planned_cumulative / datum.sum_budget',
    period='datum.sum_Installed_qty/ datum.sum_budget*100'
).mark_line(color='red').encode(
    x=alt.X("date:O", timeUnit="yearmonthdate",axis=alt.Axis(format="%d %b %y")),
    y='earned_cumulative:Q'
)
bar= line_earned.mark_bar(color='black').encode(
        y='period:Q'
)  
line_planned= line_earned.mark_line(color="green").encode(
        y='planned_cumulative:Q'
)  
text = bar.mark_text(
    align='center',
    baseline='middle',
    dx=3  # Nudges text to right so it doesn't appear on top of the bar
                ).encode(text='period:Q') 

combo = alt.layer(
    bar+ text,
    line_earned+line_planned
     ).resolve_scale(y='independent')
    
    
chart= alt.hconcat(
    barselect,
    combo
).resolve_legend(
    color="independent",
    size="independent"
)

chart.save('commodity.html')

```

```{r echo=FALSE}
shiny::includeHTML("commodity.html") 
file.remove("commodity.html")
```

map (leaflet)
=====================================



```{r}
library(readxl)
library(dplyr)
library(leaflet)
library(htmlwidgets)

#read pile  Data

pile_file <- read_excel("data/pile.xlsx", col_types = c("text","text", "numeric", "numeric","text","text"))


#filter only pile with progress

pile <- filter(pile_file,pile_file$status !="Not Started")

#read json

map_shape <- geojsonio::geojson_read("foundation.json",what = "sp")


#read foundation  data status 

foundation_data <- read_excel("data/foundation.xlsx", col_types = c("text","text","text", "numeric", "text","text"))

#merge foundation progress status with the shapefile


map_data <- sp::merge(map_shape, foundation_data, by="id")

foundation <-subset(map_data,map_data$structure=="foundation")

road <-subset(map_data,map_data$structure=="road")


#get uniquev values of status and color 

chartlegend <- unique(foundation_data[c("status", "color")])


#define a color palette 

pal <- colorFactor(
  palette = chartlegend$color,
  domain = chartlegend$status,
  ordered = TRUE
)

#define label 

labels <- sprintf(
  "<strong>%s</strong><br/><strong>%s</strong><br/>Progress %g ",
  foundation$description,foundation$status,foundation$progress
) %>% lapply(htmltools::HTML)

#Draw the map

map <-leaflet(map_data) %>%
  setView(lng = mean(pile$x), lat = (min(pile$y)+max(pile$y))/2,zoom = 15) %>%
  
  
  addTiles(urlTemplate = "https://mts1.google.com/vt/lyrs=s&hl=en&src=app&x={x}&y={y}&z={z}&s=G", attribution = 'Google') %>%
  
  addPolygons(data=foundation,fillOpacity = 1,color=foundation$color,label = labels,group="foundation")%>%
  
  addPolygons(data=road,fillOpacity = 1,color=road$color,group="road")%>%
  
  addCircleMarkers(lng = pile$x, lat = pile$y,radius = 3,group="pile")%>%
  
  addLegend(pal = pal, values = chartlegend$status, opacity = 1) %>%

  groupOptions("pile", zoomLevels = 18:21) %>%
  
  addLayersControl(position="topleft",
                 overlayGroups = c("road","foundation"),
                 options = layersControlOptions(collapsed = FALSE)
                  )
  

map

```

table (datatable)
=====================================



```{r}

library(DT)

table <- datatable(foundation_data,rownames = FALSE,extensions = 'Buttons', options = list(
  dom = 'Bfrtip',
  buttons = c('copy', 'excel')
))
table

```


